# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-TXN-Props
version:      1.01
version_from: lib/SVN/TXN/Props.pm
installdirs:  site
requires:
    SVN::Base:                     
    Test::MockClass:               1.04
    Test::More:                    0.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
